public enum GameStartTeamRequirement
{
	TWO_TEAMS_ONE_PLAYER = 0,
	TWO_TEAMS_TWO_PLAYERS = 1,
	TWO_TEAMS_THREE_PLAYERS = 2,
	TWO_TEAMS_FOUR_PLAYERS = 3,
	THREE_TEAMS_ONE_PLAYER = 4,
	THREE_TEAMS_TWO_PLAYERS = 5,
	FOUR_TEAMS_ONE_PLAYER = 6,
	FOUR_TEAMS_TWO_PLAYERS = 7,
	ONE_TEAM_ANY_PLAYERS = 8,
	ONE_TEAM_TWO_PLAYERS = 9
}
