namespace Steamworks
{
	public enum EControllerActionOrigin
	{
		k_EControllerActionOrigin_None = 0,
		k_EControllerActionOrigin_A = 1,
		k_EControllerActionOrigin_B = 2,
		k_EControllerActionOrigin_X = 3,
		k_EControllerActionOrigin_Y = 4,
		k_EControllerActionOrigin_LeftBumper = 5,
		k_EControllerActionOrigin_RightBumper = 6,
		k_EControllerActionOrigin_LeftGrip = 7,
		k_EControllerActionOrigin_RightGrip = 8,
		k_EControllerActionOrigin_Start = 9,
		k_EControllerActionOrigin_Back = 10,
		k_EControllerActionOrigin_LeftPad_Touch = 11,
		k_EControllerActionOrigin_LeftPad_Swipe = 12,
		k_EControllerActionOrigin_LeftPad_Click = 13,
		k_EControllerActionOrigin_LeftPad_DPadNorth = 14,
		k_EControllerActionOrigin_LeftPad_DPadSouth = 15,
		k_EControllerActionOrigin_LeftPad_DPadWest = 16,
		k_EControllerActionOrigin_LeftPad_DPadEast = 17,
		k_EControllerActionOrigin_RightPad_Touch = 18,
		k_EControllerActionOrigin_RightPad_Swipe = 19,
		k_EControllerActionOrigin_RightPad_Click = 20,
		k_EControllerActionOrigin_RightPad_DPadNorth = 21,
		k_EControllerActionOrigin_RightPad_DPadSouth = 22,
		k_EControllerActionOrigin_RightPad_DPadWest = 23,
		k_EControllerActionOrigin_RightPad_DPadEast = 24,
		k_EControllerActionOrigin_LeftTrigger_Pull = 25,
		k_EControllerActionOrigin_LeftTrigger_Click = 26,
		k_EControllerActionOrigin_RightTrigger_Pull = 27,
		k_EControllerActionOrigin_RightTrigger_Click = 28,
		k_EControllerActionOrigin_LeftStick_Move = 29,
		k_EControllerActionOrigin_LeftStick_Click = 30,
		k_EControllerActionOrigin_LeftStick_DPadNorth = 31,
		k_EControllerActionOrigin_LeftStick_DPadSouth = 32,
		k_EControllerActionOrigin_LeftStick_DPadWest = 33,
		k_EControllerActionOrigin_LeftStick_DPadEast = 34,
		k_EControllerActionOrigin_Gyro_Move = 35,
		k_EControllerActionOrigin_Gyro_Pitch = 36,
		k_EControllerActionOrigin_Gyro_Yaw = 37,
		k_EControllerActionOrigin_Gyro_Roll = 38,
		k_EControllerActionOrigin_Count = 39
	}
}
